# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://localhost:5432/devdb
# spring.datasource.username=devuser
# spring.datasource.password=devpass

# spring.datasource.hikari.maximum-pool-size=4
# spring.datasource.platform=postgres
# spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/devdb
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql: true
